// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDElLiA4Gpacxqocizq9S4P5rJ4cvfNVEo',
    appId: '1:335546361333:web:32ec890b3194b055bb2cbc',
    messagingSenderId: '335546361333',
    projectId: 'office-monitoring-ai',
    authDomain: 'office-monitoring-ai.firebaseapp.com',
    storageBucket: 'office-monitoring-ai.firebasestorage.app',
    measurementId: 'G-P0HC62V1HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzSHW0Ql0QnPgQfNuDu07QKzpummDg5p4',
    appId: '1:335546361333:android:754fdedb3af558b7bb2cbc',
    messagingSenderId: '335546361333',
    projectId: 'office-monitoring-ai',
    storageBucket: 'office-monitoring-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr1yKH4mBdP18JnqanIgaOXMbtU2c8lSw',
    appId: '1:335546361333:ios:bdd9982396e42382bb2cbc',
    messagingSenderId: '335546361333',
    projectId: 'office-monitoring-ai',
    storageBucket: 'office-monitoring-ai.firebasestorage.app',
    iosBundleId: 'com.example.workGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr1yKH4mBdP18JnqanIgaOXMbtU2c8lSw',
    appId: '1:335546361333:ios:bdd9982396e42382bb2cbc',
    messagingSenderId: '335546361333',
    projectId: 'office-monitoring-ai',
    storageBucket: 'office-monitoring-ai.firebasestorage.app',
    iosBundleId: 'com.example.workGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDElLiA4Gpacxqocizq9S4P5rJ4cvfNVEo',
    appId: '1:335546361333:web:19eae3ab922efc35bb2cbc',
    messagingSenderId: '335546361333',
    projectId: 'office-monitoring-ai',
    authDomain: 'office-monitoring-ai.firebaseapp.com',
    storageBucket: 'office-monitoring-ai.firebasestorage.app',
    measurementId: 'G-JQ9QXJCWZY',
  );
}
